apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: simulator-redis-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: replica
      app.kubernetes.io/instance: redis
      app.kubernetes.io/name: redis

